/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppMovementsRouteImport } from './routes/_app/movements'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppCashClosesRouteImport } from './routes/_app/cash-closes'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppCashClosesRoute = AppCashClosesRouteImport.update({
  id: '/cash-closes',
  path: '/cash-closes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash-closes': typeof AppCashClosesRoute
  '/inventory': typeof AppInventoryRoute
  '/movements': typeof AppMovementsRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash-closes': typeof AppCashClosesRoute
  '/inventory': typeof AppInventoryRoute
  '/movements': typeof AppMovementsRoute
  '/login': typeof AuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/cash-closes': typeof AppCashClosesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/movements': typeof AppMovementsRoute
  '/_auth/login': typeof AuthLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cash-closes' | '/inventory' | '/movements' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cash-closes' | '/inventory' | '/movements' | '/login'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/cash-closes'
    | '/_app/inventory'
    | '/_app/movements'
    | '/_auth/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/movements': {
      id: '/_app/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-closes': {
      id: '/_app/cash-closes'
      path: '/cash-closes'
      fullPath: '/cash-closes'
      preLoaderRoute: typeof AppCashClosesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCashClosesRoute: typeof AppCashClosesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMovementsRoute: typeof AppMovementsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashClosesRoute: AppCashClosesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMovementsRoute: AppMovementsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
